name: linux-armv6
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  workflow_dispatch:
jobs:
  linux-armv6:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        target: [
          arm-unknown-linux-gnueabihf
         ]
    steps:
    - uses: actions/checkout@v2
    - name: Build Wheels
      uses: uraimo/run-on-arch-action@v2
      with:
        arch: armv6
        distro: bullseye
        githubToken: ${{ github.token }}
        install: |
          apt-get update
          apt-get install -y python3 python3-dev python3-pip libatomic1
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain nightly-2022-11-20 -y
          source "$HOME/.cargo/env"
          pip install maturin
          CARGO_NET_GIT_FETCH_WITH_CLI=true maturin build --release --strip --out dist --target ${{ matrix.target }}